version: '3.1'

services:
  skychat:
    build: .
    ports:
      - "31337:18080"
    networks:
      - app_db
    depends_on:
      - db
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app_db

networks:
  app_db:
    driver: bridge

volumes:
  postgres_data:
